default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: betting_development
  username: postgres
  password:
test:
  <<: *default
  database: betting_test

production:
  <<: *default
  database: betting_production
  username: betting
  password: <%= ENV["BETTING_DATABASE_PASSWORD"] %>
